######################################################################
# Automatically generated by qmake (2.01a) mer. 25. juin 17:13:47 2008
######################################################################

TEMPLATE = app
CONFIG += C++11
QT += network
QT += widgets
TARGET = btnavalle
DEPENDPATH += .
INCLUDEPATH += .
#
# Input
HEADERS += FenClient.h
FORMS += FenClient.ui
SOURCES += FenClient.cpp main.cpp
